/*
 * OpenAPI Petstore
 *
 * This is a sample server Petstore server. For this sample, you can use the api key &#x60;special-key&#x60; to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

//! Authentication and middleware for OpenAPI Petstore
//!

use salvo::prelude::*;
use serde::{Deserialize, Serialize};
use base64::{engine::general_purpose::STANDARD as BASE64_STANDARD, Engine as _};



/// API Key authentication middleware
#[derive(Debug, Clone)]
pub struct ApiKeyAuth {
    pub key_name: String,
    pub api_key: String,
}

impl ApiKeyAuth {
    pub fn new(key_name: impl Into<String>, api_key: impl Into<String>) -> Self {
        Self {
            key_name: key_name.into(),
            api_key: api_key.into(),
        }
    }
}

#[async_trait::async_trait]
impl Handler for ApiKeyAuth {
    async fn handle(&self, req: &mut Request, depot: &mut Depot, res: &mut Response, ctrl: &mut FlowCtrl) {
        let provided_key = req.headers().get(&self.key_name)
            .and_then(|v| v.to_str().ok());

        if let Some(key) = provided_key {
            if key == self.api_key {
                ctrl.call_next(req, depot, res).await;
                return;
            }
        }

        res.status_code(StatusCode::UNAUTHORIZED);
        res.render("Unauthorized: Invalid API Key");
        ctrl.skip_rest();
    }
}



/// Create authentication middleware
pub fn auth_middleware() -> impl Handler {
    // Configure your authentication method here
    // Example: ApiKeyAuth::new("X-API-Key", "your-api-key")
    // Example: BasicAuth::new("username", "password")
    // Example: BearerAuth::new("your-bearer-token")

    BasicAuth::new("admin", "password") // Default example - change this!
}

