/*
 * OpenAPI Petstore
 *
 * This is a sample server Petstore server. For this sample, you can use the api key &#x60;special-key&#x60; to test the authorization filters.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 * Generated by: https://openapi-generator.tech
 */

//! API routing module
//!
//! This module defines the routing configuration for all API endpoints.

use salvo::prelude::*;
use crate::handlers::*;

/// Create the main router with all API routes
pub fn create_router() -> Router {
    let mut router = Router::new();

    // Routes for /pet
    router = router.push(
        Router::with_path("/pet")
            .put(update_pet)
            .post(add_pet)
    );
    // Routes for /pet/findByStatus
    router = router.push(
        Router::with_path("/pet/findByStatus")
            .get(find_pets_by_status)
    );
    // Routes for /pet/findByTags
    router = router.push(
        Router::with_path("/pet/findByTags")
            .get(find_pets_by_tags)
    );
    // Routes for /pet/{petId}
    router = router.push(
        Router::with_path("/pet/{petId}")
            .get(get_pet_by_id)
            .post(update_pet_with_form)
            .delete(delete_pet)
    );
    // Routes for /pet/{petId}/uploadImage
    router = router.push(
        Router::with_path("/pet/{petId}/uploadImage")
            .post(upload_file)
    );
    // Routes for /store/inventory
    router = router.push(
        Router::with_path("/store/inventory")
            .get(get_inventory)
    );
    // Routes for /store/order
    router = router.push(
        Router::with_path("/store/order")
            .post(place_order)
    );
    // Routes for /store/order/{orderId}
    router = router.push(
        Router::with_path("/store/order/{orderId}")
            .get(get_order_by_id)
            .delete(delete_order)
    );
    // Routes for /user
    router = router.push(
        Router::with_path("/user")
            .post(create_user)
    );
    // Routes for /user/createWithArray
    router = router.push(
        Router::with_path("/user/createWithArray")
            .post(create_users_with_array_input)
    );
    // Routes for /user/createWithList
    router = router.push(
        Router::with_path("/user/createWithList")
            .post(create_users_with_list_input)
    );
    // Routes for /user/login
    router = router.push(
        Router::with_path("/user/login")
            .get(login_user)
    );
    // Routes for /user/logout
    router = router.push(
        Router::with_path("/user/logout")
            .get(logout_user)
    );
    // Routes for /user/{username}
    router = router.push(
        Router::with_path("/user/{username}")
            .get(get_user_by_name)
            .put(update_user)
            .delete(delete_user)
    );

    router
}
